### ISSUE TITLE
Cannot install on x86 systems

### ISSUE THREAD

**Issue by minhducsun2002** [dungwinux/helectron#1]
As the title says.
![image](https://user-images.githubusercontent.com/32769878/36468822-8a53406a-1717-11e8-9ed1-efeffa56435c.png)

**Comment by dungwinux** [comment]
The Setup is built for x64, nothing is wrong here. If you want x86 version, you can build from source.

**Comment by dungwinux** [comment]
Future Windows setup will support both x86 and x64
